### ISSUE TITLE
Support for popup on feature click

### ISSUE THREAD

**Issue by viliam-durina** [VOL3/v-ol3#33]
Is it possible to display a ballon upon clicking on feature? I mean this feature: http://openlayers.org/en/master/examples/icon.html. Ideally the ballon should contain Vaadin components, but even HTML text would be enough for now...

Or could you give me advice to add support for this to the addon?

**Comment by viliam-durina** [comment]
I started to implement it. I started with adding support for ol.Overlay. It took me quite a lot of time, because I'm new to vaadin client development as well as to OpenLayers. Currently I'm stuck with hanging widgetset compilation: it remains forever at "Compiling permutation 0..." and cannot resolve it for few hours.

If you wish to take a look, I commited it to my fork: https://github.com/viliam-durina/v-ol3/commit/e936a1a245c86a836bc8c590e443efa5e9fa8d43. Code is untested as I cannot compile it.

**Comment by mhosio** [comment]
Hello,

Your code looks very nice and clean to me. You have a bug in your
OLOverlayConnector.getWidget(), though, that is probably the reason for
hanging compilation and would be a problem on runtime as well. Just call
super.getWidget() and cast to OverlayWidget instead.

Regards,
Matti

**Comment by viliam-durina** [comment]
Thanks, that helped. Now it compiles, but as soon as I add single overlay, the map initially draws scaled tiles, seems like by factor of 2:
![img1](https://cloud.githubusercontent.com/assets/9109877/7391118/abc5bd6e-ee7e-11e4-9c18-72fc1115439c.png)
After resizing the window, it immediately corrects itself:
![img2](https://cloud.githubusercontent.com/assets/9109877/7391119/abc6c60a-ee7e-11e4-8a78-164e10114650.png)

And, most importantly, the overlay is not visible. I suspect handling the element in OverlayWidget or that the code in OLOverlayConnector.onConnectorHierarchyChange is not correct. 

I add the overlay like this:
        OLOverlay overlay = new OLOverlay();
        Label lbl = new Label("<b>Test</b>", ContentMode.HTML);
        overlay.setContent(lbl);
        overlay.setPosition(new OLCoordinate(0, 0));
        map.addOverlay(overlay);

Thanks for help, maybe we could together add new functionality to the addon.

**Comment by mhosio** [comment]
Sorry for delay - looking into this now. Did you already get this fixed in
your fork? At least your last commit looks pretty good to me.

**Comment by viliam-durina** [comment]
Okay, I finished the overlay functionality. It has some issues:
- the vaadin button in the overlay does not have click event handler
- some overlayPositions do not work, namely only "bottom-left", "center-left" and "top-*"

If you want, I can create pull request. I'm going on with feature-click.

**Comment by viliam-durina** [comment]
Feature click done, just testing it. New information: overlayPosition work, but the overlay appears only after I move the map a bit. Still not sure why.

**Comment by mhosio** [comment]
Sounds a bit weird. Moving a map triggers canvas repaint but also does a
server roundtrip to update the current view extent. You could try to call
map.render() after adding the overlay to make sure that the problem is not
related to open layers api itself.

**Comment by mhosio** [comment]
Also, took a quick look at your fork. I saw you are passing native java double arrays to JavaScriptObjects. I don't think that works. You need to convert them to JsArrays or modify the api so that instead you pass two doubles / integers and create the array in the native method.

**Comment by viliam-durina** [comment]
Thanks, I fixed it. Now, feature click is complete. I did not thoroughly test it, but it works in my case. I simplified it that I send only the featureId back to the server, and only the first feature (this is what I saw doing in most javascript examples and it's sufficient for my case). I even send to server clicks on no feature (in my case to hide the overlay - the baloon).

Now I realize I probably did not have to add the feature click, I could do it via "select mode" and listening to selection changes...

If you wish, you can merge my fork, and do necessary cleanup/api alterations/fixes. I will be glad to use the "official" version instead of our fork.

**Comment by viliam-durina** [comment]
By the way, vaadin Buttons inside overlay still don't work. As of my investigation, they just don't sink events the same way as Buttons that are not on a map, see the screenshot from firefox developer tools. A working button:
![working_button](https://cloud.githubusercontent.com/assets/9109877/7495959/93a169b6-f411-11e4-9741-a7529c476477.png)

A button inside a map overlay does not have event handlers:
![not_working_button](https://cloud.githubusercontent.com/assets/9109877/7495962/974b8e2a-f411-11e4-9ccd-d8117774716d.png)

Don't you have an idea what could cause this? By debugging in superdevmode I could not find anything. Or give me a hint how to debug it, there is little information on vaadin custom component development on the Internet.

**Comment by mhosio** [comment]
Hello,

Checked your code but unfortunately did not find anything obvious.
Debugging in superdevmode with chrome and source maps is your best chance
here, but that type of bugs are pretty hard to debug even that way.
Unfortunately I am very busy at the moment with other projects, so can not
help you more with this one. Please let me know if you get it solved,
otherwise I'll try to give it another look later on.

-Matti

**Comment by mhosio** [comment]
By the way, very glad that you are working with the add-on. I would be more
that happy to merge your work to the main project. Have you already signed
the Vaadin contribution agreement? Since the sources of the project are
owned by Vaadin, that needs to be done before I can accept pull requests
from you.

https://vaadin.com/static/contrib/Vaadin_Contribution_Agreement.pdf

Best regards,
Matti

**Comment by viliam-durina** [comment]
I still had one problem, and thus the click is sent to server only after some mouse movement is made after the click.

I tracked it down to an incorrect call to `$entry()`: it needs a function object, that it will wrap and return another function, that you should call. I.e. you need to write `$entry(function)()` instead of `$entry(function())`. Side effect of not doing this correctly is that commands set using Scheduler.get().scheduleFinally() don't get executed until next correct call to $entry. See https://github.com/viliam-durina/v-ol3/commit/86f9065c06b1c81247c4ccf10fb214448b041eec.

You have this problem in your code as well, I will create pull request for this.

**Comment by viliam-durina** [comment]
I cannot create a pull request, since I already committed to master in my fork... Here is a patch: https://gist.github.com/viliam-durina/49368434e394ec7f19e0

**Comment by mhosio** [comment]
Thank you! I will include the fix in the next version of the add-on.

Nicely spotted!

-Matti
